In [24]:
import pyPI as pi
import numpy as np

In [37]:
import numpy as np

# Función para crear mapas de vectores Jones simulados
def create_vector_matrix(vector, shape):
    return np.array([[vector for _ in range(shape[1])] for _ in range(shape[0])])

# Vectores Jones originales
Er = (1/np.sqrt(2)) * np.array([[1], [1j]])
Es = np.array([0 - 0.7071j, 4.3298e-17 + 0.7071j])

# Crear mapas de vectores Jones
sample_shape = (100, 100)  # Tamaño del mapa (ejemplo)
A = create_vector_matrix(Er, sample_shape)
E_s = create_vector_matrix(Es, sample_shape)

# Flatten para mantener consistencia con el código original
E_r = np.stack([[elem.flatten() for elem in row] for row in A])
E_s = np.stack([[elem.flatten() for elem in row] for row in E_s])

# Intensidad calculada correctamente
b = np.sum(np.abs(E_r)**2, axis=-1) + np.sum(np.abs(E_s)**2, axis=-1)

# Producto punto calculado correctamente
m = np.abs(np.einsum('ijk,ijk->ij', E_r, np.conj(E_s)))

print(f"b (|A|² + |B|²): {b.mean()}")  # Debe ser aproximadamente 2
print(f"m (|A . B|): {m.mean()}")      # Debe ser aproximadamente 1


b (|A|² + |B|²): 1.9999808200000002
m (|A . B|): 0.7071


In [53]:
Er

array([[0.70710678+0.j        ],
       [0.        +0.70710678j]])

In [52]:
pi.field_notation(Er)

array([[ 7.07110000e-01+0.j     ],
       [-2.59736006e-06+0.70711j]])

In [50]:
pi.field_notation(A[0,0],p=True)

0.70711
0.70711
0.5π



array([[ 7.07110000e-01+0.j     ],
       [-2.59736006e-06+0.70711j]])

array([[0.70710678+0.j],
       [0.70710678+0.j]])